OPDEF(OPCODE_IF   , 15)
OPDEF(OPCODE_WHILE, 16)
OPDEF(OPCODE_FOR  , 17)
OPDEF(OPCODE_FOR_INFO  , 18)
OPDEF(OPCODE_RET  , 19)

OPDEF(OPCODE_LE   , 5)
OPDEF(OPCODE_GE   , 6)
OPDEF(OPCODE_EQ   , 7)
OPDEF(OPCODE_NEQ  , 8)
OPDEF(OPCODE_OR   , 10)
OPDEF(OPCODE_AND  , 11)

OPDEF(OPCODE_VAR_DEF, 20)
OPDEF(OPCODE_ARR_DEF, 21)
OPDEF(OPCODE_ARR_INFO, 22)
OPDEF(OPCODE_ARR_ASGN, 23)

OPDEF(OPCODE_IF_CONDITION,   30)
OPDEF(OPCODE_COND_DEPENDENT, 31)

OPDEF(OPCODE_WHILE_CONDITION, 34)
OPDEF(OPCODE_WHILE_BODY, 35)

OPDEF(OPCODE_ELEM_PUTN   , 100)
OPDEF(OPCODE_ELEM_PUTC   , 101)
OPDEF(OPCODE_ELEM_INPUT  , 102)
OPDEF(OPCODE_ELEM_MALLOC , 103)
OPDEF(OPCODE_ELEM_EXIT   , 104)

OPDEF(OPCODE_VAR , 200)
OPDEF(OPCODE_FUNC, 201)
OPDEF(OPCODE_EXPR, 202)
OPDEF(OPCODE_DEFAULT_ARG, 203)
OPDEF(OPCODE_CONTEXT_ARG, 204)

OPDEF(OPCODE_FUNC_INFO, 300)
OPDEF(OPCODE_FUNC_DECL, 301)
OPDEF(OPCODE_FUNC_CALL, 302)
OPDEF(OPCODE_FUNC_ARG_DECL, 305)
OPDEF(OPCODE_FUNC_ARG_CALL, 306)

OPDEF(OPCODE_MAX_, 500)